name: pubdev_mcp
description: A MCP server that helps you find and search for packages on pub.dev through natural language queries
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  mcp_dart: ^0.3.6
  pub_api_client: ^3.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
